server:
  port: 9080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 100
      test-while-idle: true
      validation-query: SELECT 1
      min-evictable-idle-time-millis: 300000 # 5分鐘空閑則回收
  application:
    #服务名称尽量用-，不用_，更加不用特殊字符
    name: user-center
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        cluster-name: GZ
        metadata:
          version: v1 #自己这个实例的版本
          target-version: v1 #允许调用的提供者版本（白话文：v1版本的内容中心允许调用哪个版本的用户中心）
        #namespace: 8c078bf1-4864-4413-b300-de6b605635a6